pub use rustls::SupportedCipherSuite;

use crate::dtls12::Tls12CipherSuite;
use crate::dtls12::{
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
};

// Ciphers taken from rustls::ALL_CIPHER_SUITES,
// cross-referenced with https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml
pub static ALL_DTLS_READY_CIPHER_SUITES: &[SupportedCipherSuite] = &[
    // DTLS1.2 suites
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
];

pub static DEFAULT_CIPHER_SUITES: &[SupportedCipherSuite] = ALL_DTLS_READY_CIPHER_SUITES;
